name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemGr/security-keys-action@v1
        continue-on-error: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk

          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython

      - name: Build
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ArnavDownloader-APK
          path: bin/*.apk
